### ISSUE TITLE
mConnection.requestWait() block when data length==32

### ISSUE THREAD

**Issue by yaphone** [mik3y/usb-serial-for-android#331] opened 2020-12-10 16:13 UTC
Hi,
I used usb-serial-for-android lib with a ch340 hardware, it recieve data from ch340, when the data length is not 32 or 32 * n, it works well, but it DOS NOT work when the data length is 32 or 32*n like "hellohellohellohellohellohellohe" (length = 32) or "hellohellohellohellohellohellohehellohellohellohellohellohellohe"(length = 64) . I debug it, found it block at `mConnection.requestWait()`.

And I set  `usbSerialPort.setParameters(115200, 8, UsbSerialPort.STOPBITS_1, UsbSerialPort.PARITY_NONE);`

Very strange problem, anyone can help? 

Thank U very much!

**Comment by kai-morich** [comment] 2020-12-15 07:14
Do you use `SerialInputOutputManager`? There it is normal that `read` without timeout typically blocks to fetch next data. If you use `read` in your main thread, you better use timeout to return the available data.

**Comment by yaphone** [comment] 2020-12-16 08:27
I tried to set timeout like `usbSerialPort.read(response, 1000)`, but still not work, it still can't recieve data when length==32，just cause an exception. And I also tried the example of this project, not work too. And finally I use [the driver provided by original factory](http://www.wch.cn/products/CH340.html), it works well.

I still don't know why...

**Comment by kai-morich** [comment] 2020-12-20 14:36
I could not reproduce this issue with my CH34x test devices, there was no problem with length=32.
As the vendor does not provide a full data sheet, it's unclear what might be wrong.

**Comment by yaphone** [comment] 2020-12-20 16:09
Maybe, I am the only one with this problem, so  I think it is not representative. You can close this problem if If you think it is necessary.

Thank you all the same~~  💯

**Comment by cofung** [comment] 2021-03-11 10:42
I have the same issue, it block at mConnection.requestWait(), and after close the port, it receive the data from onNewData().

**Comment by kai-morich** [comment] 2021-03-13 08:01
now I could reproduce the issue.
please try `read()` with buffer size 32 instead of 8192 as used in example app.
with this size the issue was gone. 

I can only speculate about the reason:
* The CH34x uses an USB packet size of 32 bytes. If less data is available the Android/Linux USB library immediately returns the available data. If a full packet is available it tries to read the next packet. With `bulkTransfer` I got a -1 after the timeout and the data was lost. Later send data was correctly recieved.

The issue did not occur with other device types (FTDI, Prolific, ...)

**Comment by yaphone** [comment] 2021-03-22 06:50
THX@kai-morich

Finally I used the driver which provid by the original factory, I will try it again next time when I use ch34X chip.

THX all the same!

**Comment by kai-morich** [comment] 2021-04-08 16:29
for SerialInputOutputManager fixed with https://github.com/mik3y/usb-serial-for-android/commit/848d4e771398eeecbe953d716588ba3924780c88

**Comment by xmutzlq** [comment] 2021-04-29 03:09
i have the same issue,  when i send "11111111111111111111111111111111111111111111112"，the "2" is not receive，then i try to send "111111111111111111111111111111111111111111111122"，data is full receive，i do not know how to resolve，can you help me？

**Comment by kai-morich** [comment] 2021-04-29 05:23
when using SerialInputOutputManager you do not have to set the buffer size any more, as it already sets the optimal size = 32.

**Comment by xmutzlq** [comment] 2021-04-30 01:59
we have resolved yesterday，cause write data timeout is too short，we have increased timeout, finally it works well
thank you @kai-morich

**Closed** 2021-05-02 06:42 UTC
Labels: device:ch34x
