### ISSUE TITLE
Leak in CommonUsbSerialPort close method assumed by Android StrictMode class

### ISSUE THREAD

**Issue by tom42530** [mik3y/usb-serial-for-android#460] opened 2022-11-23 16:43 UTC
Hi,

first thanks for your amazing work.

Seen with strict mode enable aka : StrictMode.enableDefaults(); 
Ressource mUsbRequest is never closed
close method only cancel and set it to null but never call close to release associated ressource.
To fix it simply call mUsbRequest.close l.143

Thanks in advance

**Comment by kai-morich** [comment] 2022-11-25 07:44
I couldnt reproduce the StrictMode output, only got other unrelated StrictMode output.
Closing the usbRequest earlier causes strange NullPointer Exceptions inside Android USB functions.
As the object is closed by the finalizer, I keep as is.

**Closed** 2022-11-25 07:45 UTC
